#!/bin/sh
set -eu

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS notification_db COLLATE utf8mb4_0900_as_ci;
CREATE DATABASE IF NOT EXISTS alert_processor_db COLLATE utf8mb4_0900_as_ci;

CREATE USER IF NOT EXISTS '${NOTIFICATION_DB_USER}'@'%' IDENTIFIED BY '${NOTIFICATION_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${ALERT_PROCESSOR_DB_USER}'@'%' IDENTIFIED BY '${ALERT_PROCESSOR_DB_PASSWORD}';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES ON notification_db.* TO '${NOTIFICATION_DB_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES, TRIGGER ON alert_processor_db.* TO '${ALERT_PROCESSOR_DB_USER}'@'%';
SQL
